package com.consultingplatform.model.payment;

import com.consultingplatform.model.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * UC5 – Process Payment / UC7 – View Payment History
 *
 * Class diagram fields (exact):
 *   - id            : String         → UUID, auto-generated on persist
 *   - booking       : Booking        → bookingId (FK placeholder until Booking entity exists)
 *   - strategy      : PaymentStrategy → @Transient, not persisted
 *   - amount        : double         → BigDecimal for DB precision
 *   - transactionId : String         → unique, generated by each PaymentStrategy
 *   - timestamp     : DateTime       → LocalDateTime, set on persist
 *
 * Additional persisted fields:
 *   - clientId      – needed for UC7 history queries scoped per client
 *   - strategyType  – persists strategy.getPaymentType() for UC7 reporting
 *   - status        – PENDING | COMPLETED | FAILED | REFUNDED
 */
@Entity
@Table(name = "payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

    @Id
    private String id;

    @Column(name = "booking_id", nullable = false)
    private Long bookingId;

    @Column(name = "client_id", nullable = false)
    private Long clientId;

    /** Held in memory during processing – NOT persisted. */
    @Transient
    private PaymentStrategy strategy;

    /** Persisted form of strategy.getPaymentType() e.g. "CREDIT_CARD". */
    @Column(name = "strategy_type", nullable = false)
    private String strategyType;

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false, unique = true)
    private String transactionId;

    @Column(nullable = false)
    private LocalDateTime timestamp;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;

    private String failureReason;

    @PrePersist
    protected void onCreate() {
        if (id == null)        id        = UUID.randomUUID().toString();
        if (timestamp == null) timestamp = LocalDateTime.now();
        if (status == null)    status    = PaymentStatus.PENDING;
    }
}
